# Generated by Django 3.2.3 on 2021-07-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
