# Generated by Django 3.2.3 on 2021-07-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('imagen_cat', models.ImageField(blank=True, upload_to='photos/categorias')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
    ]
